apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: sample-tomcat
spec:
  replicas: 1
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: sample-tomcat
    spec:
      containers:
      - image: innovatecloud.dst.ibm.com:8500/nextgen-tooling/sample-tomcat:latest
        name: sample-tomcat
        ports:
        - containerPort: 8080
        resources:
          limits:
           cpu: 200m
           memory: 500Mi
          requests:
            cpu: 200m
            memory: 500Mi
      restartPolicy: Always
status: {}
