apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    name: sample-tomcat
  name: sample-tomcat-svc
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
    nodePort: 30904
  selector:
    name: sample-tomcat
  type: NodePort
